### ISSUE TITLE
美图秀秀集成不进去

### ISSUE THREAD

**Issue by freshman13141** [Xposed-Modules-Repo/Hook.JiuWu.Xp#29]
Launch patch
, Processing /data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched.apk
, apk path: /data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk
, Parsing original apk...
, Failed to read zip file '/data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk'.
, java.io.IOException: Failed to read zip file '/data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk'.
	at y4.y.<init>(Unknown Source:223)
	at y4.t.<init>(Unknown Source:6)
	at a9.a.a(Unknown Source:325)
	at h8.b.g(Unknown Source:23)
	at k7.a.u(Unknown Source:5)
	at z7.e0.run(Unknown Source:109)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(Unknown Source:76)
Caused by: java.io.IOException: Cannot read entry 'assets/apple/light3D/photography/ar/configuration.resources' (offset: 180897589, size: 271) because it overlaps with 'assets/MaterialCenter/video_edit_beauty/FillLight/face/ar/configuration.resources' (offset: 180897161, size: 699)
	at y4.y.P(Unknown Source:868)
	at y4.y.<init>(Unknown Source:155)
	... 8 more

**Comment by lovejiuwu** [comment]
模块问题 与模块无关
________________________________
发件人: ***@***.*** ***@***.***> 代表 freshman13141 ***@***.***>
发送时间: 2024年6月7日 16:15
收件人: Xposed-Modules-Repo/Hook.JiuWu.Xp ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Xposed-Modules-Repo/Hook.JiuWu.Xp] 美图秀秀集成不进去 (Issue #29)


Launch patch
, Processing /data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched.apk
, apk path: /data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk
, Parsing original apk...
, Failed to read zip file '/data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk'.
, java.io.IOException: Failed to read zip file '/data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk'.
at y4.y.(Unknown Source:223)
at y4.t.(Unknown Source:6)
at a9.a.a(Unknown Source:325)
at h8.b.g(Unknown Source:23)
at k7.a.u(Unknown Source:5)
at z7.e0.run(Unknown Source:109)
at kotlinx.coroutines.internal.e.run(Unknown Source:11)
at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
at kotlinx.coroutines.scheduling.a.run(Unknown Source:76)
Caused by: java.io.IOException: Cannot read entry 'assets/apple/light3D/photography/ar/configuration.resources' (offset: 180897589, size: 271) because it overlaps with 'assets/MaterialCenter/video_edit_beauty/FillLight/face/ar/configuration.resources' (offset: 180897161, size: 699)
at y4.y.P(Unknown Source:868)
at y4.y.(Unknown Source:155)
... 8 more

―

**Comment by lovejiuwu** [comment]
框架问题 与模块无关
________________________________
发件人: ***@***.*** ***@***.***> 代表 freshman13141 ***@***.***>
发送时间: 2024年6月7日 16:15
收件人: Xposed-Modules-Repo/Hook.JiuWu.Xp ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Xposed-Modules-Repo/Hook.JiuWu.Xp] 美图秀秀集成不进去 (Issue #29)


Launch patch
, Processing /data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched.apk
, apk path: /data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk
, Parsing original apk...
, Failed to read zip file '/data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk'.
, java.io.IOException: Failed to read zip file '/data/app/com.mt.mtxx.mtxx-oPszvuGFTZZDunKQg4WCdw==/base.apk'.
at y4.y.(Unknown Source:223)
at y4.t.(Unknown Source:6)
at a9.a.a(Unknown Source:325)
at h8.b.g(Unknown Source:23)
at k7.a.u(Unknown Source:5)
at z7.e0.run(Unknown Source:109)
at kotlinx.coroutines.internal.e.run(Unknown Source:11)
at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
at kotlinx.coroutines.scheduling.a.run(Unknown Source:76)
Caused by: java.io.IOException: Cannot read entry 'assets/apple/light3D/photography/ar/configuration.resources' (offset: 180897589, size: 271) because it overlaps with 'assets/MaterialCenter/video_edit_beauty/FillLight/face/ar/configuration.resources' (offset: 180897161, size: 699)
at y4.y.P(Unknown Source:868)
at y4.y.(Unknown Source:155)
... 8 more

―

**Comment by 13098724567** [comment]
免root的就别叫唤了😅

**Comment by 13098724567** [comment]
> 免root的就别叫唤了😅

没root玩什么XP模块
