### ISSUE TITLE
模块无法启动，反复闪退

### ISSUE THREAD

**Issue by hyplant** [Xposed-Modules-Repo/Hook.JiuWu.Xp#41]
今天突然发现wx中的功能失效了，打开模块，结果模块闪退，重启手机也没有效果
抓取到的日志如下
```
Crash unexpectedly: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	... 1 more
Caused by: java.lang.Throwable: 已失效
	at Hook.JiuWu.Xp.ui.MContext.<init>(Unknown Source:28)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at androidx.core.app.CoreComponentFactory.instantiateApplication(Unknown Source:0)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1177)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1456)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:158)
	at LSPHooker_.makeApplication(Unknown Source:18)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7458)
	at android.app.ActivityThread.access$1700(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	... 3 more
```
就看到一个已失效，也不知道怎么回事，希望尽快修复

**Comment by xiaojianjian-huang** [comment]
我也闪退了，有解决办法吗
